on:
  workflow_dispatch:

name: generate_pkg_list_pyenv

jobs:
  generate_pkg_list_pyenv:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: windows-latest}
        - {os: ubuntu-latest}
        - {os: macos-15-intel}
        - {os: macos-latest}
        - {os: ubuntu-24.04-arm}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Build environment
        if: runner.os == 'Linux'
        run: |
          python3 -m venv python==3.13.3 ./footprintr-env
          source ./footprintr-env/bin/activate
          python3 -m pip install 'tensorflow[and-cuda]' keras h5py

      - name: Build environment
        if: runner.os != 'Linux'
        run: |
          python3 -m venv python==3.13.3 ./footprintr-env
          source ./footprintr-env/bin/activate
          python3 -m pip install tensorflow==2.19.0 keras h5py

      - name: List content of environment
        run: pip3 list ./footprintr-env

      # - name: List content of environment in format suitable for pasting into R
      #   if: runner.os != 'Windows'
      #   run: |
      #     conda list -p ./sketchr-env | tail -n +4 |\
      #     tr -s ' ' | cut -f1,2 -d' ' |\
      #     sed -e 's/ /==/' -e 's/^..*$/"&",/' -e '$ s/.$/)/' -e '1s/^/c(/'
